### ISSUE TITLE
Great looking project - how to try

### ISSUE THREAD

**Issue by docop** [alptugan/3D-Studies-with-openFrameworks#2]
Hi So i found your project and it's look very interesting and quite nice. But as i'm not coding expert.. how can this be run ? Is all need to be run inside a Visual studio and then it emulate an output or it can be export as an own program after.. or so ? thanks in advance

**Comment by alptugan** [comment]
Hi,
All of the projects written in C++ using openFrameworks (open source toolkit for C++). You can download & compile the projects with openFrameworks. And yes, you need a IDE like Visual Studio Code. Check out the [openFrameworks website](https://openframeworks.cc). there are instructions, tutorials and examples that tell you how you can manage it to work
