### ISSUE TITLE
Code for example image of "2- Generate plane geometry with ofMesh from scratch." please

### ISSUE THREAD

**Issue by MarkParker5** [alptugan/3D-Studies-with-openFrameworks#3]
![image](https://raw.githubusercontent.com/alptugan/3D-Studies-with-openFrameworks/master/2_generate3DPlaneMeshPoints/generate_plane_vertices_coordinates.png)

**Comment by alptugan** [comment]
Updated. Thanks for the issue!
The code is so dirty. I will update the whole folder asap.
https://github.com/alptugan/3D-Studies-with-openFrameworks/tree/master/2_generate3DPlaneMeshPoints
